// <auto-generated />
using BookStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20220224024144_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("BookStore.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Classic"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Biography"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Historical"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Self-Help"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Business"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Thrillers"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Christian Books"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Health"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Action"
                        });
                });

            modelBuilder.Entity("BookStore.Models.Classification", b =>
                {
                    b.Property<int>("ClassificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassificationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClassificationID");

                    b.ToTable("Classification");

                    b.HasData(
                        new
                        {
                            ClassificationID = 1,
                            ClassificationName = "Fiction"
                        },
                        new
                        {
                            ClassificationID = 2,
                            ClassificationName = "Non-Fiction"
                        });
                });

            modelBuilder.Entity("BookStore.Models.FormResponse", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassificationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumPage")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ISBN");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ClassificationID");

                    b.ToTable("FormResponses");

                    b.HasData(
                        new
                        {
                            ISBN = "978-0451419439",
                            Author = "Victor Hugo",
                            CategoryID = 7,
                            ClassificationID = 1,
                            NumPage = 1488,
                            Price = 9.9499999999999993,
                            Publisher = "Signet",
                            Title = "Les Miserables"
                        },
                        new
                        {
                            ISBN = "978-0743270755",
                            Author = "Doris Kearns Goodwin",
                            CategoryID = 2,
                            ClassificationID = 2,
                            NumPage = 944,
                            Price = 14.58,
                            Publisher = "Simon & Schuster",
                            Title = "Team of Rivals"
                        },
                        new
                        {
                            ISBN = "978-0553384611",
                            Author = "Alice Schroeder",
                            CategoryID = 2,
                            ClassificationID = 2,
                            NumPage = 832,
                            Price = 21.539999999999999,
                            Publisher = "Bantam",
                            Title = "The Snowball"
                        },
                        new
                        {
                            ISBN = "978-0812981254",
                            Author = "Ronald C. White",
                            CategoryID = 2,
                            ClassificationID = 2,
                            NumPage = 864,
                            Price = 11.609999999999999,
                            Publisher = "Random House",
                            Title = "American Ulysses"
                        },
                        new
                        {
                            ISBN = "978-0812974492",
                            Author = "Laura Hillenbrand",
                            CategoryID = 3,
                            ClassificationID = 2,
                            NumPage = 528,
                            Price = 13.33,
                            Publisher = "Random House",
                            Title = "Unbroken"
                        },
                        new
                        {
                            ISBN = "978-0804171281",
                            Author = "Michael Crichton",
                            CategoryID = 3,
                            ClassificationID = 1,
                            NumPage = 288,
                            Price = 13.33,
                            Publisher = "Vintage",
                            Title = "The Great Train Robbery"
                        },
                        new
                        {
                            ISBN = "978-1455586691",
                            Author = "Cal Newport",
                            CategoryID = 4,
                            ClassificationID = 1,
                            NumPage = 304,
                            Price = 14.99,
                            Publisher = "Grand Central Publishing",
                            Title = "Deep Work"
                        },
                        new
                        {
                            ISBN = "978-1455523023",
                            Author = "Michael Abrashoff",
                            CategoryID = 4,
                            ClassificationID = 2,
                            NumPage = 240,
                            Price = 21.66,
                            Publisher = "Grand Central Publishing",
                            Title = "It's Your Ship"
                        },
                        new
                        {
                            ISBN = "978-1591847984",
                            Author = "Richard Branson",
                            CategoryID = 5,
                            ClassificationID = 2,
                            NumPage = 400,
                            Price = 29.16,
                            Publisher = "Portfolio",
                            Title = "The Virgin Way"
                        },
                        new
                        {
                            ISBN = "978-0553393613",
                            Author = "John Grisham",
                            CategoryID = 6,
                            ClassificationID = 1,
                            NumPage = 642,
                            Price = 15.029999999999999,
                            Publisher = "Batnam",
                            Title = "Sycamore Row"
                        },
                        new
                        {
                            ISBN = "978-1982131470",
                            Author = "Mike Rowe",
                            CategoryID = 3,
                            ClassificationID = 1,
                            NumPage = 272,
                            Price = 12.300000000000001,
                            Publisher = "Gallery Books",
                            Title = "The Way I Heard It"
                        },
                        new
                        {
                            ISBN = "978-1481216043",
                            Author = "Ulysses S. Grant",
                            CategoryID = 2,
                            ClassificationID = 2,
                            NumPage = 552,
                            Price = 19.989999999999998,
                            Publisher = "CreateSpace Independent Publishing Platform",
                            Title = "The Complete Personal Memoirs of Ulysses S. Grant"
                        },
                        new
                        {
                            ISBN = "978-0060652937",
                            Author = "C.S. Lewis",
                            CategoryID = 7,
                            ClassificationID = 1,
                            NumPage = 209,
                            Price = 10.27,
                            Publisher = "HarperOne",
                            Title = "The Screwtape Letters"
                        },
                        new
                        {
                            ISBN = "978-1623367398",
                            Author = "Shawn Stevenson",
                            CategoryID = 8,
                            ClassificationID = 2,
                            NumPage = 288,
                            Price = 17.59,
                            Publisher = "Rodale Books",
                            Title = "Sleep Smarter"
                        },
                        new
                        {
                            ISBN = "978-1400077304",
                            Author = "Ron Chernow",
                            CategoryID = 2,
                            ClassificationID = 2,
                            NumPage = 832,
                            Price = 16.59,
                            Publisher = "Vintage",
                            Title = "Titan"
                        },
                        new
                        {
                            ISBN = "978-0440001027",
                            Author = "Tom Clancy",
                            CategoryID = 9,
                            ClassificationID = 2,
                            NumPage = 656,
                            Price = 9.9900000000000002,
                            Publisher = "Berkley",
                            Title = "The Hunt for Red October"
                        });
                });

            modelBuilder.Entity("BookStore.Models.FormResponse", b =>
                {
                    b.HasOne("BookStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Models.Classification", "Classification")
                        .WithMany()
                        .HasForeignKey("ClassificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
