// <auto-generated />
using BookStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20220218000440_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("BookStore.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Classic"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Biography"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Historical"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Self-Help"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Business"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Thrillers"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Christian Books"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Health"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Action"
                        });
                });

            modelBuilder.Entity("BookStore.Models.Classification", b =>
                {
                    b.Property<int>("ClassificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassificationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClassificationID");

                    b.ToTable("Classification");

                    b.HasData(
                        new
                        {
                            ClassificationID = 1,
                            ClassificationName = "Fiction"
                        },
                        new
                        {
                            ClassificationID = 2,
                            ClassificationName = "Non-Fiction"
                        });
                });

            modelBuilder.Entity("BookStore.Models.FormResponse", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassificationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumPage")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ISBN");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ClassificationID");

                    b.ToTable("FormResponses");

                    b.HasData(
                        new
                        {
                            ISBN = "978-0451419439",
                            Author = "Victor Hugo",
                            CategoryID = 7,
                            ClassificationID = 1,
                            NumPage = 1488,
                            Price = 9.9499999999999993,
                            Publisher = "Signet",
                            Title = "Les Miserables"
                        });
                });

            modelBuilder.Entity("BookStore.Models.FormResponse", b =>
                {
                    b.HasOne("BookStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Models.Classification", "Classification")
                        .WithMany()
                        .HasForeignKey("ClassificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
